spring:

  h2:
    console:
      enabled: true

  datasource:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:test
    #    username: sa
    #    password:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test;
      username: sa
      password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: true

logging:
  level:
    org:
      springframework:
        security: debug
    com.toycode: debug

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400