spring:

  h2:
    console:
      enabled: true

  datasource:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:test
    #    username: sa
    #    password:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test;
      username: sa
      password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: true

logging:
  level:
    org.springframework.security: debug
    com.toycode: debug

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
    disable-swagger-default-url: true
    doc-expansion: none
  default-consumes-media-type: application/json
  properties:
    title: Springboot 3.0.4 with Spring Security 6.0.2
    version: 3.0.4
    description: 스프링부트와 시큐리티를 학습하기 위한 프로젝트입니다.(Hexagonal Architecture)
    name: toycode
    email: toycode727@gmail.com
    url: https://hyeonseokhan.github.io/resume/

app:
  api:
    version: /api/v1
  security:
    enabled: true
    exclude:
      api-paths:
        - /api/v1/user/register
        - /api/v1/auth/login
        - /api/v1/auth/logout
        - /swagger-ui/**
        - /v*/api-docs/**
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds: 86400

