spring:

  h2:
    console:
      enabled: true

  datasource:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:test
    #    username: sa
    #    password:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test;
      username: sa
      password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      #      naming:
      #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: true

logging:
  level:
    org:
      springframework:
        security: debug
    com.toycode: debug

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
    disable-swagger-default-url: true
    doc-expansion: none
  default-consumes-media-type: application/json
  properties:
    title: Springboot 2.6.2 with Spring Security 5.6.1
    version: 2.6.2
    description: 스프링부트와 시큐리티를 학습하기 위한 프로젝트입니다.
    name: toycode
    email: toycode727@gmail.com
    url: https://hyeonseokhan.github.io/resume/

app:
  security:
    enabled: true
    include:
      api-paths:
        - /api/v*/**
    exclude:
      api-paths:
        - /api/v1/auth/**
        - /api/v1/demo/get
        - /swagger-ui
        - /v*/api-docs/**
        - /swagger-resources/**
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds: 86400